---

variables:
  GIT_SUBMODULE_STRATEGY: none
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

stages:
  - precheck
  - basic-tests
  - full-tests
  - deploy

.basetest: &testbaseanchor
  stage: basic-tests

  # cache:
  #   key: tavern-project-cache
  #   paths:
  #     - .cache/pip
  #     - .tox
  #   policy: pull

  before_script:
    - pip install tox
  script:
    - tox -c ${TOXCFG} -e ${CI_JOB_NAME}

  variables:
    TOXCFG: tox.ini

  only:
    - master


########################################
# Initial checks
########################################

.flakestest: &flakestest
  <<: *testbaseanchor
  stage: precheck

py27flakes:
  <<: *flakestest
  image: python:2.7-alpine

py36flakes:
  <<: *flakestest
  image: python:3.6-alpine


########################################
# Unit tests
########################################

.basictests: &basictest
  <<: *testbaseanchor


# basic unit tests
py27:
  <<: *basictest
  image: python:2.7-alpine

py36:
  <<: *basictest
  image: python:3.6-alpine

  # Make this job push the cache. It doesn't hugely matter if the cache is out
  # of date, so just do it in one job.
  # cache:
  #   key: tavern-project-cache
  #   paths:
  #     - .cache/pip
  #     - .tox

py27lint:
  <<: *basictest
  image: python:2.7-alpine

py36lint:
  <<: *basictest
  image: python:3.6-alpine


# extra unit tests
py34:
  <<: *basictest
  image: python:3.4-alpine
  stage: full-tests

py35:
  <<: *basictest
  image: python:3.5-alpine
  stage: full-tests

pypy:
  <<: *basictest
  image: pypy:2-slim
  stage: full-tests

pypy3:
  <<: *basictest
  image: pypy:3-slim
  stage: full-tests


########################################
# Integration tests
########################################

# Different cfg file and needs docker running
.integrationtest: &inttest
  <<: *testbaseanchor
  variables:
    TOXCFG: tox-integration.ini
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:dind
  before_script:
    - pip install --upgrade docker-compose tox


# basic integration tests
py27-generic:
  <<: *inttest
  image: python:2.7-alpine

py36-mqtt:
  <<: *inttest
  image: python:3.6-alpine

py36-advanced:
  <<: *inttest
  image: python:3.6-alpine

py36-generic:
  <<: *inttest
  image: python:3.6-alpine


# full integration tests
py27-cookies:
  <<: *inttest
  image: python:2.7-alpine
  stage: full-tests

py34-cookies:
  <<: *inttest
  image: python:3.4-alpine
  stage: full-tests

py35-cookies:
  <<: *inttest
  image: python:3.5-alpine
  stage: full-tests

py36-cookies:
  <<: *inttest
  image: python:3.6-alpine
  stage: full-tests

pypy-cookies:
  <<: *inttest
  image: pypy:2-slim
  stage: full-tests

pypy3-cookies:
  <<: *inttest
  image: pypy:3-slim
  stage: full-tests


########################################
# Deploy
########################################

Deploy to pypi:
  <<: *testbaseanchor

  only:
    - tags

  stage: deploy
  image: python:2.7-alpine
  before_script:
    - |
        echo "
        [distutils]
        index-servers =
            pypi

        [pypi]
        repository = https://pypi.python.org/pypi
        username = ${PYPI_USERNAME}
        password = ${PYPI_PASSWORD}
        " > ~/.pypirc

    - pip install twine
  script:
    - python setup.py sdist bdist_wheel --universal
    - twine upload dist/*
