inherits:
  - strictness_veryhigh

output-format: pylint

test-warnings: true
doc-warnings: true

pep8:
  run: false
mccabe:
  run: false

ignore-paths:
  - venv
  - .tox
  - docs
  - example
  - tests/integration
  - build
  - .pytest_cache
  - tavern.egg_info
