---
name: Request HTTP schemas
desc: pykwalify schemas for request and response

request:
  request:
    type: map
    required: false
    mapping:
      url:
        type: str
        required: true

      re;(params|data|headers):
        include: any_map_with_ext_function

      json:
        include: any_map_or_list_with_ext_function

      method:
        type: str
        enum:
          - GET
          - PUT
          - POST
          - DELETE
          - PATCH
          - OPTIONS
          - HEAD

      verify:
        type: bool
        required: false

response:
  response:
    type: map
    required: false
    mapping:
      status_code:
        type: int

      cookies:
        type: seq
        required: false
        sequence:
          - type: str
            unique: true

      re;(headers|redirect_query_params):
        include: any_map_with_ext_function

      body:
        include: any_map_or_list_with_ext_function

      save:
        include: any_map_with_ext_function
        mapping:
          re;(\$ext|body|headers|redirect_query_params):
            type: any
